services:
  server:
    build:
      dockerfile: server/Dockerfile
      context: .
      args:
        NODE_ENV: development
    env_file: server/.env
    volumes:
      - ./server:/app/server
    entrypoint: ["yarn", "run", "start:dev"]
    ports:
      - "8050:80"

  frontend:
    build: 
      dockerfile: frontend/Dockerfile
      context: .
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
  
  db:
    image: mongo
    volumes:
      - db:/data/db
      - db:/data/configdb
    ports:
      - "27017:27017"

volumes:
  db: