name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  migrate-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn --pure-lockfile
      - name: Run migrations
        working-directory: mongo-migrate
        run: yarn run up
        env:
          MIGRATIONS_CONNECTION_URI: ${{ secrets.MIGRATIONS_CONNECTION_URI }}
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build server
        working-directory: server
        run: yarn run build
      - name: Build frontend
        working-directory: frontend
        run: yarn run build

  deploy:
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: stuckinabox
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: stuckinabox/rehearsal-manager:latest
          file: server/Dockerfile